title = "~/nezia"
base_url = "https://nezia.dev"
default_language = "en"

theme = "tabi"
compile_sass = true
build_search_index = false

hard_link_static = true

[markdown]
highlight_code = true

[extra]
favicon_emoji = "💻"
encode_plaintext_email = true
email = "anthony@nezia.dev"
socials = [
        { name = "github", url = "https://github.com/nezia1", icon = "github"}
]
projects_path = "projects/_index.md"

menu = [
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "resume", url = "resume.pdf", trailing_slash = false }
]
