baseurl                  = "https://nezia.dev"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Anthony Rodriguez"
theme                    = "github.com/victoriadrake/hugo-theme-sam"    # pull in theme as hugo module 
# theme                  = "sam"                      # install theme locally (git clone or submodule)
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                           # What to call the home page link, link will not be rendered if empty
#    footerText           = "Call me Sam, a theme for Hugo."

# Metadata for Open Graph and Twitter
    description          = "Hi, I'm Anthony Rodriguez."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Portfolio"
    # rss                = ""

[[params.mainMenu]]
    link = "about"
    text = "about me"

[[params.mainMenu]]
    link = "projects"
    text = "projects"

[[params.mainMenu]]
    link = "https://github.com/nezia1"
    text = "github"
    
[[params.mainMenu]]
    link = "resume"
    text = "resume"

[imaging]
    quality = 75
